name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: xd009642/tarpaulin:develop

    steps:
      - uses: actions/checkout@v2

      - name: Install SDL2 and Python
        run: apt install -y python3 libsdl2-dev

      - name: Generate code coverage
        run: ./cargo-tarpaulin tarpaulin --verbose --no-default-features --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
